### ISSUE TITLE
Error in creating DB !

### ISSUE THREAD

**Issue by aayushkansal** [hasgeek/hasjob#208] opened 2015-07-29 07:06 UTC
I am getting this error while running  "python manage.py db create". 

Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    from hasjob.models import db
  File "/home/ayush/projects/hasjob/hasjob/__init__.py", line 12, in <module>
    from baseframe import baseframe, assets, Version
  File "/usr/local/lib/python2.7/dist-packages/baseframe/__init__.py", line 216, in <module>
    from .views import *    # NOQA
  File "/usr/local/lib/python2.7/dist-packages/baseframe/views.py", line 12, in <module>
    from .forms import Form
  File "/usr/local/lib/python2.7/dist-packages/baseframe/forms/__init__.py", line 12, in <module>
    from .validators import *
  File "/usr/local/lib/python2.7/dist-packages/baseframe/forms/validators.py", line 6, in <module>
    import dns.resolver
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 35, in <module>
    import dns.message
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 191
    print('id %d' % self.id, file=s)
                                 ^
SyntaxError: invalid syntax

**Comment by jace** [comment] 2015-07-29 07:20
Dupe of #207.

**Closed by jace** 2015-07-29 07:20 UTC
